<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Barrio;

class BarrioSeeder extends Seeder
{ public function run(): void
    {

        $barrios = [
['nombre'=>'Mishqui Mayu', 'localidad_id' =>140],
['nombre'=>'Parque Industrial Mishqui', 'localidad_id' =>140],
['nombre'=>'Salta Prolongacion', 'localidad_id' =>140],
['nombre'=>'Juan D. Peron', 'localidad_id' =>140],
['nombre'=>'Textil', 'localidad_id' =>140],
['nombre'=>'Mercantil', 'localidad_id' =>140],
['nombre'=>'Villa Nueva', 'localidad_id' =>140],
['nombre'=>'17 de Octubre', 'localidad_id' =>140],
['nombre'=>'Besares', 'localidad_id' =>140],
['nombre'=>'Los Alamos I', 'localidad_id' =>140],
['nombre'=>'Los Alamos II', 'localidad_id' =>140],
['nombre'=>'Dorrego', 'localidad_id' =>140],
['nombre'=>'Villa Union', 'localidad_id' =>140],
['nombre'=>'Salido', 'localidad_id' =>140],
['nombre'=>'Central Argentino', 'localidad_id' =>140],
['nombre'=>'Los Lagos', 'localidad_id' =>140],
['nombre'=>'25 de Mayo', 'localidad_id' =>140],
['nombre'=>'Nuevo 25 de Mayo', 'localidad_id' =>140],
['nombre'=>'Avenida', 'localidad_id' =>140],
['nombre'=>'9 de Julio', 'localidad_id' =>140],
['nombre'=>'San Fernando', 'localidad_id' =>140],
['nombre'=>'La Guarida', 'localidad_id' =>140],
['nombre'=>'Rio Dulce', 'localidad_id' =>140],
['nombre'=>'Ampliacion 25 de Mayo', 'localidad_id' =>140],
['nombre'=>'Tradicion', 'localidad_id' =>2],
['nombre'=>'Congreso', 'localidad_id' =>2],
['nombre'=>'Sarmiento', 'localidad_id' =>2],
['nombre'=>'Ramon Carrillo', 'localidad_id' =>2],
['nombre'=>'Cabildo', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno Viejo', 'localidad_id' =>2],
['nombre'=>'Francisco de Aguirre', 'localidad_id' =>2],
['nombre'=>'America del Sur', 'localidad_id' =>2],
['nombre'=>'Saenz PeÃ±a', 'localidad_id' =>2],
['nombre'=>'Rivadavia', 'localidad_id' =>2],
['nombre'=>'Bruno Volta', 'localidad_id' =>2],
['nombre'=>'Don Bosco', 'localidad_id' =>2],
['nombre'=>'Santa Rosa de Lima', 'localidad_id' =>2],
['nombre'=>'Jardin', 'localidad_id' =>2],
['nombre'=>'Los Flores3 - 300Viviendas', 'localidad_id' =>2],
['nombre'=>'Ejercito Argentino', 'localidad_id' =>2],
['nombre'=>'Smata', 'localidad_id' =>2],
['nombre'=>'Siglo XXI', 'localidad_id' =>2],
['nombre'=>'Reconquista', 'localidad_id' =>2],
['nombre'=>'Centro', 'localidad_id' =>2],
['nombre'=>'Juan Bautista Alberdi', 'localidad_id' =>2],
['nombre'=>'General Paz', 'localidad_id' =>2],
['nombre'=>'Palomar', 'localidad_id' =>2],
['nombre'=>'La Fraternidad', 'localidad_id' =>140],
['nombre'=>'17 de Noviembre', 'localidad_id' =>431],
['nombre'=>'Bontempo', 'localidad_id' =>41],
['nombre'=>'Santa Rafaela', 'localidad_id' =>41],
['nombre'=>'Belgrano', 'localidad_id' =>41],
['nombre'=>'La Merced', 'localidad_id' =>41],
['nombre'=>'Rosso', 'localidad_id' =>41],
['nombre'=>'Nestor Kirchner', 'localidad_id' =>41],
['nombre'=>'Colonia Osvaldo', 'localidad_id' =>41],
['nombre'=>'Villa Nilda', 'localidad_id' =>41],
['nombre'=>'Villa Maria', 'localidad_id' =>41],
['nombre'=>'Sportivo', 'localidad_id' =>41],
['nombre'=>'Manzione', 'localidad_id' =>41],
['nombre'=>'Villa Abregu', 'localidad_id' =>41],
['nombre'=>'El Triangulo', 'localidad_id' =>41],
['nombre'=>'Norte', 'localidad_id' =>379],
['nombre'=>'Palermo', 'localidad_id' =>379],
['nombre'=>'Centro', 'localidad_id' =>379],
['nombre'=>'Bella Vista', 'localidad_id' =>379],
['nombre'=>'PanorÃ¡mico', 'localidad_id' =>379],
['nombre'=>'Talleres Oeste', 'localidad_id' =>379],
['nombre'=>'Talleres Ampliacion', 'localidad_id' =>379],
['nombre'=>'Municipal', 'localidad_id' =>379],
['nombre'=>'Avellaneda Sur', 'localidad_id' =>439],
['nombre'=>'Ampliacion Santa Lucia', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno 1Âº Amp', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno 3Âº Amp', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno Residencial', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno 6Âº Amp', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno 4Âº Amp', 'localidad_id' =>2],
['nombre'=>'Asentamiento Mariano Moreno', 'localidad_id' =>2],
['nombre'=>'San Jose de Flores', 'localidad_id' =>2],
['nombre'=>'AESYA Ej. Arg.', 'localidad_id' =>2],
['nombre'=>'Municipal Ej. Arg.', 'localidad_id' =>2],
['nombre'=>'40 Viviendas Ej. Arg.', 'localidad_id' =>2],
['nombre'=>'Departamentos3 Ej. Arg.', 'localidad_id' =>2],
['nombre'=>'Departamentos1 Eje. Arg.', 'localidad_id' =>2],
['nombre'=>'Bosco II', 'localidad_id' =>2],
['nombre'=>'Bosco I', 'localidad_id' =>2],
['nombre'=>'2Âº Ampliacion Borges', 'localidad_id' =>2],
['nombre'=>'La Curva', 'localidad_id' =>41],
['nombre'=>'Parque', 'localidad_id' =>41],
['nombre'=>'La Laguna', 'localidad_id' =>41],
['nombre'=>'Sumampa Norte', 'localidad_id' =>41],
['nombre'=>'Banda Verde', 'localidad_id' =>41],
['nombre'=>'Villa Paulina', 'localidad_id' =>41],
['nombre'=>'Centenario', 'localidad_id' =>41],
['nombre'=>'Las Violetas', 'localidad_id' =>41],
['nombre'=>'Miguel Salim', 'localidad_id' =>41],
['nombre'=>'Belgrano', 'localidad_id' =>219],
['nombre'=>'Virgen del Valle', 'localidad_id' =>41],
['nombre'=>'Juan y Eva Peron', 'localidad_id' =>41],
['nombre'=>'Alborada', 'localidad_id' =>288],
['nombre'=>'Campo Rosso', 'localidad_id' =>288],
['nombre'=>'Obrero', 'localidad_id' =>288],
['nombre'=>'C.G.T.', 'localidad_id' =>288],
['nombre'=>'Villa Nilda', 'localidad_id' =>288],
['nombre'=>'Nestor Kirchner', 'localidad_id' =>288],
['nombre'=>'Rosso', 'localidad_id' =>288],
['nombre'=>'La Merced', 'localidad_id' =>288],
['nombre'=>'Belgrano', 'localidad_id' =>288],
['nombre'=>'Las Malvinas', 'localidad_id' =>288],
['nombre'=>'Villa Abregu', 'localidad_id' =>288],
['nombre'=>'Maipu', 'localidad_id' =>237],
['nombre'=>'Irigoyen', 'localidad_id' =>237],
['nombre'=>'NULL', 'localidad_id' =>237],
['nombre'=>'San Martin', 'localidad_id' =>237],
['nombre'=>'Colon', 'localidad_id' =>237],
['nombre'=>'San Antonio', 'localidad_id' =>237],
['nombre'=>'21 de Septiembre', 'localidad_id' =>237],
['nombre'=>'Malvinas Argentinas', 'localidad_id' =>237],
['nombre'=>'J. Hernandez', 'localidad_id' =>237],
['nombre'=>'Hospital', 'localidad_id' =>237],
['nombre'=>'Las Penquitas', 'localidad_id' =>237],
['nombre'=>'El Tala', 'localidad_id' =>466],
['nombre'=>'La Merced', 'localidad_id' =>466],
['nombre'=>'Palermo', 'localidad_id' =>466],
['nombre'=>'Bella Vista', 'localidad_id' =>466],
['nombre'=>'Norte', 'localidad_id' =>466],
['nombre'=>'Malvinas', 'localidad_id' =>242],
['nombre'=>'Fonavi III', 'localidad_id' =>242],
['nombre'=>'Centro', 'localidad_id' =>242],
['nombre'=>'IÃ±iguez', 'localidad_id' =>242],
['nombre'=>'Palomar', 'localidad_id' =>242],
['nombre'=>'Triangulo', 'localidad_id' =>242],
['nombre'=>'Fonavi IV', 'localidad_id' =>242],
['nombre'=>'Fonavi I', 'localidad_id' =>242],
['nombre'=>'Fonavi II', 'localidad_id' =>242],
['nombre'=>'Juan Felipe Ibarra', 'localidad_id' =>242],
['nombre'=>'San Martin', 'localidad_id' =>242],
['nombre'=>'Calasanz', 'localidad_id' =>242],
['nombre'=>'Santa Angela', 'localidad_id' =>242],
['nombre'=>'Cooperativas', 'localidad_id' =>242],
['nombre'=>'Coesa', 'localidad_id' =>2],
['nombre'=>'Usina', 'localidad_id' =>426],
['nombre'=>'Sector El Alto', 'localidad_id' =>426],
['nombre'=>'Union Ferroviaria', 'localidad_id' =>140],
['nombre'=>'Villa Gambetti', 'localidad_id' =>140],
['nombre'=>'Villa Gianuzzi', 'localidad_id' =>140],
['nombre'=>'El Cruce', 'localidad_id' =>140],
['nombre'=>'Guillermo Pohl', 'localidad_id' =>140],
['nombre'=>'Villa Rosita', 'localidad_id' =>140],
['nombre'=>'Villa Elena', 'localidad_id' =>140],
['nombre'=>'Nuestra Sra de Lourdes', 'localidad_id' =>140],
['nombre'=>'La Isla Oeste', 'localidad_id' =>140],
['nombre'=>'Amanzanamiento de Don Mariano', 'localidad_id' =>140],
['nombre'=>'Villa Suaya', 'localidad_id' =>140],
['nombre'=>'Villa Raquel', 'localidad_id' =>140],
['nombre'=>'San Javier', 'localidad_id' =>140],
['nombre'=>'Villa Manfredi', 'localidad_id' =>140],
['nombre'=>'Tabla Redonda', 'localidad_id' =>140],
['nombre'=>'Centenario', 'localidad_id' =>140],
['nombre'=>'Juan Felipe Ibarra', 'localidad_id' =>140],
['nombre'=>'El Bosque', 'localidad_id' =>140],
['nombre'=>'Inmigrantes', 'localidad_id' =>2],
['nombre'=>'San Martin', 'localidad_id' =>2],
['nombre'=>'Industria', 'localidad_id' =>2],
['nombre'=>'Madres de Plaza de Mayo', 'localidad_id' =>2],
['nombre'=>'Autonomia', 'localidad_id' =>2],
['nombre'=>'Villa del Carmen', 'localidad_id' =>2],
['nombre'=>'Los Flores2 - 268Viviendas', 'localidad_id' =>2],
['nombre'=>'Juan Diaz de Solis', 'localidad_id' =>2],
['nombre'=>'Siglo XX', 'localidad_id' =>2],
['nombre'=>'Parque Aguirre', 'localidad_id' =>2],
['nombre'=>'San Francisco Solano', 'localidad_id' =>2],
['nombre'=>'Caceres', 'localidad_id' =>2],
['nombre'=>'8 de Abril', 'localidad_id' =>2],
['nombre'=>'La Catolica', 'localidad_id' =>2],
['nombre'=>'Centenario', 'localidad_id' =>2],
['nombre'=>'Jorge Newbery', 'localidad_id' =>2],
['nombre'=>'Juan Felipe Ibarra', 'localidad_id' =>2],
['nombre'=>'Aeropuerto', 'localidad_id' =>2],
['nombre'=>'Gorrini', 'localidad_id' =>140],
['nombre'=>'Centro', 'localidad_id' =>199],
['nombre'=>'Herrera El Alto', 'localidad_id' =>426],
['nombre'=>'Paludica', 'localidad_id' =>426],
['nombre'=>'Puente Alsina', 'localidad_id' =>430],
['nombre'=>'Fatima', 'localidad_id' =>140],
['nombre'=>'Las Malvinas', 'localidad_id' =>41],
['nombre'=>'Villa Fernandez', 'localidad_id' =>41],
['nombre'=>'Campo Rosso', 'localidad_id' =>41],
['nombre'=>'Juan XXIII', 'localidad_id' =>41],
['nombre'=>'120 Viviendas', 'localidad_id' =>41],
['nombre'=>'Polo Norte', 'localidad_id' =>41],
['nombre'=>'Centro', 'localidad_id' =>41],
['nombre'=>'San Jorge', 'localidad_id' =>41],
['nombre'=>'Tiro Federal', 'localidad_id' =>41],
['nombre'=>'Obrero', 'localidad_id' =>41],
['nombre'=>'San Cayetano', 'localidad_id' =>41],
['nombre'=>'Colonia San Francisco', 'localidad_id' =>41],
['nombre'=>'Malvinas Argentinas', 'localidad_id' =>379],
['nombre'=>'Mariano Moreno 8Âº Amp', 'localidad_id' =>2],
['nombre'=>'Ampliacion Ejercito Argentino', 'localidad_id' =>2],
['nombre'=>'Tarapaya', 'localidad_id' =>2],
['nombre'=>'Villa del Carmen Usurpado', 'localidad_id' =>2],
['nombre'=>'Telefonicos', 'localidad_id' =>2],
['nombre'=>'Parque', 'localidad_id' =>2],
['nombre'=>'Gas del Estado', 'localidad_id' =>2],
['nombre'=>'24 de Septiembre', 'localidad_id' =>41],
['nombre'=>'Sumampa Sur', 'localidad_id' =>41],
['nombre'=>'Sol de Julio', 'localidad_id' =>453],
['nombre'=>'Fortabat', 'localidad_id' =>41],
['nombre'=>'Chacral', 'localidad_id' =>219],
['nombre'=>'Almirante Brown', 'localidad_id' =>41],
['nombre'=>'200 Viviendas', 'localidad_id' =>41],
['nombre'=>'Remansito', 'localidad_id' =>41],
['nombre'=>'Villa Coinor', 'localidad_id' =>41],
['nombre'=>'Oeste', 'localidad_id' =>41],
['nombre'=>'120 Viviendas', 'localidad_id' =>288],
['nombre'=>'Santa Rita', 'localidad_id' =>288],
['nombre'=>'Colonia Osvaldo', 'localidad_id' =>288],
['nombre'=>'San Jorge', 'localidad_id' =>288],
['nombre'=>'Centro', 'localidad_id' =>288],
['nombre'=>'El Triangulo', 'localidad_id' =>288],
['nombre'=>'Sportivo', 'localidad_id' =>288],
['nombre'=>'Villa Maria', 'localidad_id' =>288],
['nombre'=>'Tiro Federal', 'localidad_id' =>288],
['nombre'=>'Villa Aurora', 'localidad_id' =>237],
['nombre'=>'Norte', 'localidad_id' =>237],
['nombre'=>'Centro', 'localidad_id' =>237],
['nombre'=>'Talleres Oeste', 'localidad_id' =>466],
['nombre'=>'Panoramico', 'localidad_id' =>466],
['nombre'=>'Centro', 'localidad_id' =>466],
['nombre'=>'Los Olivos', 'localidad_id' =>242],
['nombre'=>'Dubrovich', 'localidad_id' =>242],
['nombre'=>'San Cayetano', 'localidad_id' =>242],
['nombre'=>'El Rincon', 'localidad_id' =>140],
['nombre'=>'76 viviendas', 'localidad_id' =>41],
['nombre'=>'Ampliacion Paraiso', 'localidad_id' =>140],
['nombre'=>'Toro Yacu', 'localidad_id' =>426],
['nombre'=>'EspaÃ±a', 'localidad_id' =>426],
['nombre'=>'Banfield', 'localidad_id' =>140],
['nombre'=>'Roca', 'localidad_id' =>237],
['nombre'=>'Santa Clara', 'localidad_id' =>140],
['nombre'=>'Villa Menendez', 'localidad_id' =>140],
['nombre'=>'San Martin', 'localidad_id' =>140],
['nombre'=>'Villa Eloisa', 'localidad_id' =>140],
['nombre'=>'Arturo Illia', 'localidad_id' =>140],
['nombre'=>'Villa Griselda', 'localidad_id' =>140],
['nombre'=>'Palermo', 'localidad_id' =>140],
['nombre'=>'Villa Ines', 'localidad_id' =>140],
['nombre'=>'Libertador', 'localidad_id' =>140],
['nombre'=>'Cabildo SantiagueÃ±o', 'localidad_id' =>140],
['nombre'=>'Nuevo Central Argentino', 'localidad_id' =>140],
['nombre'=>'Villa Juana', 'localidad_id' =>140],
['nombre'=>'Independencia', 'localidad_id' =>140],
['nombre'=>'El Tuscal', 'localidad_id' =>140],
['nombre'=>'El Paraiso', 'localidad_id' =>140],
['nombre'=>'Constitucion', 'localidad_id' =>140],
['nombre'=>'Sarmiento', 'localidad_id' =>140],
['nombre'=>'Centro', 'localidad_id' =>140],
['nombre'=>'Tabla Redonda Ampliacion', 'localidad_id' =>140],
['nombre'=>'Villa Jardin', 'localidad_id' =>140],
['nombre'=>'San Carlos', 'localidad_id' =>140],
['nombre'=>'Juramento', 'localidad_id' =>2],
['nombre'=>'Belgrano', 'localidad_id' =>2],
['nombre'=>'Primera Junta', 'localidad_id' =>2],
['nombre'=>'Libertad', 'localidad_id' =>2],
['nombre'=>'Santa Lucia', 'localidad_id' =>2],
['nombre'=>'Mosconi', 'localidad_id' =>2],
['nombre'=>'John Kennedy', 'localidad_id' =>2],
['nombre'=>'Belen', 'localidad_id' =>2],
['nombre'=>'Almirante Brown', 'localidad_id' =>2],
['nombre'=>'Independencia', 'localidad_id' =>2],
['nombre'=>'Los Flores IPVU 50 viviendas', 'localidad_id' =>2],
['nombre'=>'Los Flores4 - Virgen de Guadalupe - 450V', 'localidad_id' =>2],
['nombre'=>'Islas Malvinas', 'localidad_id' =>2],
['nombre'=>'Campo Contreras', 'localidad_id' =>2],
['nombre'=>'Siglo XIX', 'localidad_id' =>2],
['nombre'=>'750 Viviendas', 'localidad_id' =>2],
['nombre'=>'El Vinalar', 'localidad_id' =>2],
['nombre'=>'Sargento Cabral', 'localidad_id' =>2],
['nombre'=>'Juan XXIII', 'localidad_id' =>2],
['nombre'=>'Colon', 'localidad_id' =>2],
['nombre'=>'Huaico Hondo', 'localidad_id' =>2],
['nombre'=>'Coronel Borges', 'localidad_id' =>2],
['nombre'=>'San Germes', 'localidad_id' =>2],
['nombre'=>'Independiente', 'localidad_id' =>237],
['nombre'=>'Matadero', 'localidad_id' =>140],
['nombre'=>'Ampliacion Parque Industrial', 'localidad_id' =>140],
['nombre'=>'Mendilarzu', 'localidad_id' =>140],
['nombre'=>'El Triangulo', 'localidad_id' =>2],
['nombre'=>'Villa Balnearia', 'localidad_id' =>426],
['nombre'=>'Ampliacion 1Âº de Mayo', 'localidad_id' =>140],
['nombre'=>'Menendez', 'localidad_id' =>140],
['nombre'=>'Parque Industrial Hiper', 'localidad_id' =>140],
['nombre'=>'Alborada', 'localidad_id' =>41],
['nombre'=>'Santa Rita', 'localidad_id' =>41],
['nombre'=>'La LeÃ±era', 'localidad_id' =>41],
['nombre'=>'CGT', 'localidad_id' =>41],
['nombre'=>'Rivadavia', 'localidad_id' =>41],
['nombre'=>'La Merced', 'localidad_id' =>379],
['nombre'=>'Cristo Redentor', 'localidad_id' =>379],
['nombre'=>'Mariano Moreno 2Âº Amp', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno 7Âº Amp', 'localidad_id' =>2],
['nombre'=>'Mariano Moreno 5Âº Amp', 'localidad_id' =>2],
['nombre'=>'Villa del Carmen Nuevo', 'localidad_id' =>2],
['nombre'=>'Nuevo Banco', 'localidad_id' =>2],
['nombre'=>'Pitufos Ej. Arg.', 'localidad_id' =>2],
['nombre'=>'Departamentos 2 Ej. Arg.', 'localidad_id' =>2],
['nombre'=>'Bosco III', 'localidad_id' =>2],
['nombre'=>'Los Flores', 'localidad_id' =>2],
['nombre'=>'Ciudad del NiÃ±o', 'localidad_id' =>2],
['nombre'=>'Los Lagos', 'localidad_id' =>2],
['nombre'=>'Centro Oeste', 'localidad_id' =>41],
['nombre'=>'Eliseo Fringes', 'localidad_id' =>41],
['nombre'=>'Centro Este', 'localidad_id' =>41],
['nombre'=>'Casas Baratas', 'localidad_id' =>41],
['nombre'=>'Yapeyu', 'localidad_id' =>41],
['nombre'=>'Dr Elias Moises Morra', 'localidad_id' =>41],
['nombre'=>'Frias 2000', 'localidad_id' =>41],
['nombre'=>'Dr Carlos Juarez', 'localidad_id' =>41],
['nombre'=>'Los Sauces', 'localidad_id' =>41],
['nombre'=>'Esperanza I-II-III', 'localidad_id' =>41],
['nombre'=>'11 de Julio', 'localidad_id' =>41],
['nombre'=>'Juan XXIII', 'localidad_id' =>288],
['nombre'=>'Santa Rafaela', 'localidad_id' =>288],
['nombre'=>'Villa Fernandez', 'localidad_id' =>288],
['nombre'=>'Rivadavia', 'localidad_id' =>288],
['nombre'=>'La LeÃ±era', 'localidad_id' =>288],
['nombre'=>'Polo Norte', 'localidad_id' =>288],
['nombre'=>'Manzione', 'localidad_id' =>288],
['nombre'=>'Las Americas', 'localidad_id' =>237],
['nombre'=>'2 de Abril', 'localidad_id' =>237],
['nombre'=>'Villa Elisa', 'localidad_id' =>237],
['nombre'=>'Los Amigos', 'localidad_id' =>237],
['nombre'=>'NULL', 'localidad_id' =>237],
['nombre'=>'Los Pinos', 'localidad_id' =>237],
['nombre'=>'Fernandez', 'localidad_id' =>237],
['nombre'=>'9 de Julio', 'localidad_id' =>237],
['nombre'=>'Jardin', 'localidad_id' =>466],
['nombre'=>'Municipal', 'localidad_id' =>466],
['nombre'=>'Talleres Ampliacion', 'localidad_id' =>466],
['nombre'=>'Cristo Redentor', 'localidad_id' =>466],
['nombre'=>'Malvinas Argentinas', 'localidad_id' =>466],
['nombre'=>'Colon', 'localidad_id' =>242],
['nombre'=>'Belgrano', 'localidad_id' =>242],
['nombre'=>'Alomo', 'localidad_id' =>242],
['nombre'=>'Lujan', 'localidad_id' =>242],
['nombre'=>'Victoria', 'localidad_id' =>242],
['nombre'=>'Ezeiza', 'localidad_id' =>242],
['nombre'=>'Juan XXIII', 'localidad_id' =>242],
['nombre'=>'Los Naranjos', 'localidad_id' =>140],
['nombre'=>'Chino', 'localidad_id' =>41],
['nombre'=>'IV Centenario', 'localidad_id' =>140],
['nombre'=>'Ramos Taboada', 'localidad_id' =>140],
['nombre'=>'Municipal', 'localidad_id' =>426],
['nombre'=>'Santa Rosa', 'localidad_id' =>365],
['nombre'=>'Fatima', 'localidad_id' =>160],
['nombre'=>'Las Chacras', 'localidad_id' =>379],
['nombre'=>'El Rosedal', 'localidad_id' =>219],
['nombre'=>'Soberania Nacional', 'localidad_id' =>426],
['nombre'=>'Tradicion Este', 'localidad_id' =>2],
['nombre'=>'Comercio', 'localidad_id' =>290],
['nombre'=>'Jardin', 'localidad_id' =>290],
['nombre'=>'Oeste', 'localidad_id' =>461],
['nombre'=>'Centenario', 'localidad_id' =>461],
['nombre'=>'Centro', 'localidad_id' =>461],
['nombre'=>'Belgrano', 'localidad_id' =>35],
['nombre'=>'Centro', 'localidad_id' =>35],
['nombre'=>'Homero Manzi', 'localidad_id' =>288],
['nombre'=>'Colegiales', 'localidad_id' =>197],
['nombre'=>'Centro', 'localidad_id' =>197],
['nombre'=>'Centro', 'localidad_id' =>160],
['nombre'=>'Almirante Brown', 'localidad_id' =>160],
['nombre'=>'Agua y Energia', 'localidad_id' =>140],
['nombre'=>'1Âº de Mayo', 'localidad_id' =>140],
['nombre'=>'Bajo de Vertiz', 'localidad_id' =>140],
['nombre'=>'Platense', 'localidad_id' =>288],
['nombre'=>'Platense Oeste', 'localidad_id' =>288],
['nombre'=>'El Polear', 'localidad_id' =>140],
['nombre'=>'Agua Santa', 'localidad_id' =>426],
['nombre'=>'Adela', 'localidad_id' =>426],
['nombre'=>'San Martin', 'localidad_id' =>426],
['nombre'=>'Centro', 'localidad_id' =>426],
['nombre'=>'Usurpado', 'localidad_id' =>426],
['nombre'=>'Eva Peron', 'localidad_id' =>160],
['nombre'=>'Ricardo Rojas', 'localidad_id' =>160],
['nombre'=>'Mendilarzu', 'localidad_id' =>160],
['nombre'=>'Mailin', 'localidad_id' =>290],
['nombre'=>'Centro', 'localidad_id' =>290],
['nombre'=>'Matadero', 'localidad_id' =>290],
['nombre'=>'Libertad', 'localidad_id' =>262],
['nombre'=>'Autonomia Provincial', 'localidad_id' =>262],
['nombre'=>'Lote 40', 'localidad_id' =>290],
['nombre'=>'Arbolada', 'localidad_id' =>262],
['nombre'=>'El Tigre', 'localidad_id' =>262],
['nombre'=>'Francisco Solano', 'localidad_id' =>426],
['nombre'=>'Progreso', 'localidad_id' =>426],
['nombre'=>'Sector A', 'localidad_id' =>426],
['nombre'=>'Villa Nueva', 'localidad_id' =>426],
['nombre'=>'25 de Mayo', 'localidad_id' =>426],
['nombre'=>'Obrero', 'localidad_id' =>426],
['nombre'=>'Sector C', 'localidad_id' =>426],
['nombre'=>'Sector B', 'localidad_id' =>426],
['nombre'=>'Usurpado 2', 'localidad_id' =>426],
['nombre'=>'Norte', 'localidad_id' =>426],
['nombre'=>'Urquiza', 'localidad_id' =>426],
['nombre'=>'30 Viv. Proviso', 'localidad_id' =>426],
['nombre'=>'Dr. Carlos Juarez 12 Viv', 'localidad_id' =>426],
['nombre'=>'100 Viv Av. Urquiza (usurpado)', 'localidad_id' =>426],
['nombre'=>'80 Viviendas', 'localidad_id' =>426],
['nombre'=>'Jardin', 'localidad_id' =>426],
['nombre'=>'Los Fierros', 'localidad_id' =>426],
['nombre'=>'Santa Rita', 'localidad_id' =>426],
['nombre'=>'Salitre', 'localidad_id' =>426],
['nombre'=>'Tradicion Oeste', 'localidad_id' =>2],
['nombre'=>'Sargento Cabral', 'localidad_id' =>426],
['nombre'=>'Libertad', 'localidad_id' =>426],
['nombre'=>'Ramos Taboada', 'localidad_id' =>426],
['nombre'=>'Ampliacion Paraiso', 'localidad_id' =>426],
['nombre'=>'Parque Industrial', 'localidad_id' =>426],
['nombre'=>'Juan Diaz de Solis Usurpado', 'localidad_id' =>2],
['nombre'=>'94 Viviendas', 'localidad_id' =>41],
['nombre'=>'Alborada', 'localidad_id' =>199],
['nombre'=>'Libertad', 'localidad_id' =>199],
['nombre'=>'Virgen de Loreto', 'localidad_id' =>453],
['nombre'=>'La Darsena', 'localidad_id' =>152],
['nombre'=>'Centro', 'localidad_id' =>307],
['nombre'=>'San Expedito', 'localidad_id' =>41],
['nombre'=>'Cooperativas', 'localidad_id' =>41],
['nombre'=>'Villa Borges', 'localidad_id' =>2],
['nombre'=>'El Corralito', 'localidad_id' =>237],
['nombre'=>'Las Americas', 'localidad_id' =>237],
['nombre'=>'Virgen de Guadalupe', 'localidad_id' =>2],
['nombre'=>'La Pileta', 'localidad_id' =>426],
['nombre'=>'San Lorenzo', 'localidad_id' =>426],
['nombre'=>'Aeroclub', 'localidad_id' =>41],
['nombre'=>'Matadero Viejo', 'localidad_id' =>140],
['nombre'=>'50 Viviendas', 'localidad_id' =>426],
['nombre'=>'Ampliacion San Fernando', 'localidad_id' =>140],
['nombre'=>'Eva Peron', 'localidad_id' =>262],
['nombre'=>'40 Viviendas', 'localidad_id' =>344],
['nombre'=>'Centro', 'localidad_id' =>344],
['nombre'=>'Pueblo Nuevo', 'localidad_id' =>344],
['nombre'=>'Belen', 'localidad_id' =>307],
['nombre'=>'San Francisco', 'localidad_id' =>276],
['nombre'=>'Ciclon', 'localidad_id' =>276],
['nombre'=>'Centro', 'localidad_id' =>276],
['nombre'=>'Centro Sur', 'localidad_id' =>23],
['nombre'=>'Centro', 'localidad_id' =>23],
['nombre'=>'La Merced', 'localidad_id' =>199],
['nombre'=>'Colegiales', 'localidad_id' =>199],
['nombre'=>'Ampliacion Juan Diaz de Solis', 'localidad_id' =>2],
['nombre'=>'Ampliacion Campo Contreras', 'localidad_id' =>2],
['nombre'=>'Villa Anita', 'localidad_id' =>140],
['nombre'=>'San Martin', 'localidad_id' =>23],
['nombre'=>'50 Viviendas', 'localidad_id' =>41],
['nombre'=>'Inti Huasi', 'localidad_id' =>41],
['nombre'=>'Difunta Correa', 'localidad_id' =>199],
['nombre'=>'El Remanso', 'localidad_id' =>379],
['nombre'=>'Poligono', 'localidad_id' =>379],
['nombre'=>'Chollua', 'localidad_id' =>344],
['nombre'=>'Fonavi', 'localidad_id' =>344],
['nombre'=>'Belgrano', 'localidad_id' =>466],
['nombre'=>'Villa del Lago', 'localidad_id' =>426],
['nombre'=>'Fonavi', 'localidad_id' =>288],
['nombre'=>'Juventud', 'localidad_id' =>307],
['nombre'=>'Las Trincheras', 'localidad_id' =>307],
['nombre'=>'Mitre', 'localidad_id' =>307],
['nombre'=>'Proviso', 'localidad_id' =>365],
['nombre'=>'Centro', 'localidad_id' =>235],
['nombre'=>'Maradona', 'localidad_id' =>235],
['nombre'=>'Los Escolanos', 'localidad_id' =>152],
['nombre'=>'Zona Fabril', 'localidad_id' =>140],
['nombre'=>'San Cayetano', 'localidad_id' =>140],
['nombre'=>'17 de Octubre', 'localidad_id' =>41],
['nombre'=>'Villa Rojas', 'localidad_id' =>157],
['nombre'=>'Saint Germain', 'localidad_id' =>2],
['nombre'=>'Belgrano', 'localidad_id' =>23],
['nombre'=>'Sur', 'localidad_id' =>69],
['nombre'=>'Cooperativa', 'localidad_id' =>237],
['nombre'=>'San Juan', 'localidad_id' =>140],
['nombre'=>'Virgen del Carmen', 'localidad_id' =>453],
['nombre'=>'Santa Teresita', 'localidad_id' =>453],
['nombre'=>'Santa Rosa', 'localidad_id' =>160],
['nombre'=>'Evita', 'localidad_id' =>23],
['nombre'=>'Colegial', 'localidad_id' =>419],
['nombre'=>'Centro', 'localidad_id' =>419],
['nombre'=>'Quilmes', 'localidad_id' =>140],
['nombre'=>'Aion NÂº3', 'localidad_id' =>177],
['nombre'=>'12 de Octubre', 'localidad_id' =>237],
['nombre'=>'Ramos MejÃ­a', 'localidad_id' =>160],
['nombre'=>'25 de Mayo Ampliacion 100 Viviendas', 'localidad_id' =>140],
['nombre'=>'Boca del Tigre', 'localidad_id' =>2],
['nombre'=>'Ampliacion Independencia', 'localidad_id' =>2],
['nombre'=>'El Bajo', 'localidad_id' =>41],
['nombre'=>'Prososa', 'localidad_id' =>419],
['nombre'=>'Centro', 'localidad_id' =>125],
['nombre'=>'Centro', 'localidad_id' =>177],
['nombre'=>'Los Flores', 'localidad_id' =>237],
['nombre'=>'Santa Rita', 'localidad_id' =>237],
['nombre'=>'Comercial', 'localidad_id' =>238],
['nombre'=>'Centro', 'localidad_id' =>262],
['nombre'=>'Cooperativo', 'localidad_id' =>307],
['nombre'=>'San Jose', 'localidad_id' =>365],
['nombre'=>'Centro', 'localidad_id' =>484],
['nombre'=>'Santa Teresita', 'localidad_id' =>484],
['nombre'=>'Avellaneda', 'localidad_id' =>238],
['nombre'=>'Racedo', 'localidad_id' =>238],
['nombre'=>'Ampliacion Racedo', 'localidad_id' =>238],
['nombre'=>'Puente Alsina', 'localidad_id' =>238],
['nombre'=>'25 de Mayo', 'localidad_id' =>219],
['nombre'=>'Villa Balnearia', 'localidad_id' =>125],
['nombre'=>'Frias', 'localidad_id' =>41],
['nombre'=>'"Sector ""A"""', 'localidad_id' =>177],
['nombre'=>'Centro', 'localidad_id' =>315],
['nombre'=>'Eva Peron', 'localidad_id' =>41],
['nombre'=>'Carlos Juarez', 'localidad_id' =>41],
['nombre'=>'Aion NÂº2', 'localidad_id' =>177],
['nombre'=>'Usurpado', 'localidad_id' =>262],
['nombre'=>'El Canalito', 'localidad_id' =>237],
['nombre'=>'90 Viviendas', 'localidad_id' =>41],
['nombre'=>'Union y Progreso', 'localidad_id' =>219],
['nombre'=>'El Porvenir', 'localidad_id' =>498],
['nombre'=>'Belgrano', 'localidad_id' =>262],
['nombre'=>'Islas Malvinas', 'localidad_id' =>262],
['nombre'=>'Ampliacion Malvinas', 'localidad_id' =>262],
['nombre'=>'Ferrocarril', 'localidad_id' =>290],
['nombre'=>'Las Tres Rosas', 'localidad_id' =>242],
['nombre'=>'Ampliacion Central Argentino', 'localidad_id' =>140],
['nombre'=>'Alberdi', 'localidad_id' =>379],
['nombre'=>'Centro', 'localidad_id' =>219],
['nombre'=>'Centro', 'localidad_id' =>365],
['nombre'=>'300 Viviendas', 'localidad_id' =>140],
['nombre'=>'Centro', 'localidad_id' =>451],
['nombre'=>'El Tabique', 'localidad_id' =>140],
['nombre'=>'San Jorge', 'localidad_id' =>248],
['nombre'=>'San Cayetano', 'localidad_id' =>248],
['nombre'=>'Santa Rosa de Lima', 'localidad_id' =>248],
['nombre'=>'A. Gramajo', 'localidad_id' =>235],
['nombre'=>'San Roque', 'localidad_id' =>262],
['nombre'=>'Ademol', 'localidad_id' =>41],
['nombre'=>'Ademof', 'localidad_id' =>426],
['nombre'=>'Aeropuerto', 'localidad_id' =>365],
['nombre'=>'Ampliacion El Vinalar', 'localidad_id' =>2],
['nombre'=>'Ampliacion El Paraiso', 'localidad_id' =>262],
['nombre'=>'Arturo Illia', 'localidad_id' =>160],
['nombre'=>'25 de Mayo', 'localidad_id' =>16],
['nombre'=>'30 Viviendas', 'localidad_id' =>237],
['nombre'=>'30 Viviendas', 'localidad_id' =>41],
['nombre'=>'50 Viviendas', 'localidad_id' =>262],
['nombre'=>'60 Viviendas', 'localidad_id' =>426],
['nombre'=>'84 Viviendas', 'localidad_id' =>379],
['nombre'=>'90 Viviendas', 'localidad_id' =>2],
['nombre'=>'Campo Contreras Viejo', 'localidad_id' =>2],
['nombre'=>'Capitolio', 'localidad_id' =>160],
['nombre'=>'Canal', 'localidad_id' =>160],
['nombre'=>'Centenario', 'localidad_id' =>365],
['nombre'=>'Centro', 'localidad_id' =>16],
['nombre'=>'Chimpa', 'localidad_id' =>267],
['nombre'=>'ChaÃ±arito', 'localidad_id' =>309],
['nombre'=>'Colonia San Francisco', 'localidad_id' =>288],
['nombre'=>'Corvalan', 'localidad_id' =>288],
['nombre'=>'Coronel Borges', 'localidad_id' =>140],
['nombre'=>'Corvalan', 'localidad_id' =>290],
['nombre'=>'Costa del Sol', 'localidad_id' =>426],
['nombre'=>'Don Bosco', 'localidad_id' =>2],
['nombre'=>'Ejercito Argentino', 'localidad_id' =>2],
['nombre'=>'El Alto', 'localidad_id' =>426],
['nombre'=>'El Pescadito', 'localidad_id' =>426],
['nombre'=>'Eva Peron', 'localidad_id' =>426],
['nombre'=>'Galeano', 'localidad_id' =>426],
['nombre'=>'General Paz', 'localidad_id' =>140],
['nombre'=>'General Paz', 'localidad_id' =>2],
['nombre'=>'Hermanos Wagner', 'localidad_id' =>309],
['nombre'=>'Hermanos Wagner', 'localidad_id' =>307],
['nombre'=>'Independencia', 'localidad_id' =>2],
['nombre'=>'Islas Malvinas', 'localidad_id' =>365],
['nombre'=>'Islas Malvinas', 'localidad_id' =>237],
['nombre'=>'Islas Malvinas', 'localidad_id' =>288],
['nombre'=>'Jardin', 'localidad_id' =>2],
['nombre'=>'Jorge Gotau', 'localidad_id' =>315],
['nombre'=>'Juan Bautista Alberdi', 'localidad_id' =>426],
['nombre'=>'Juan Bautista Alberdi', 'localidad_id' =>379],
['nombre'=>'Juan D. Peron', 'localidad_id' =>289],
['nombre'=>'Villa Nueva', 'localidad_id' =>160],
['nombre'=>'Libarona', 'localidad_id' =>426],
['nombre'=>'San Cayetano', 'localidad_id' =>23],
['nombre'=>'El Porvenir', 'localidad_id' =>23],
['nombre'=>'Lopez Agrello', 'localidad_id' =>307],
['nombre'=>'Boca', 'localidad_id' =>276],
['nombre'=>'San Cayetano', 'localidad_id' =>403],
['nombre'=>'Centro', 'localidad_id' =>403],
['nombre'=>'Virgen del Carmen', 'localidad_id' =>453],
['nombre'=>'Virgen del Carmen', 'localidad_id' =>484],
['nombre'=>'Alborada', 'localidad_id' =>419],
['nombre'=>'Matadero', 'localidad_id' =>419],
['nombre'=>'Jerarquizado Municipal', 'localidad_id' =>2],
['nombre'=>'Este', 'localidad_id' =>403],
['nombre'=>'Norte', 'localidad_id' =>344],
['nombre'=>'San Cayetano', 'localidad_id' =>199],
['nombre'=>'16 Viviendas', 'localidad_id' =>199],
['nombre'=>'Cuatro', 'localidad_id' =>266],
['nombre'=>'Aion NÂº1', 'localidad_id' =>177],
['nombre'=>'Villa Rojas', 'localidad_id' =>140],
['nombre'=>'El Municipal', 'localidad_id' =>23],
['nombre'=>'Centro', 'localidad_id' =>309],
['nombre'=>'Ferro', 'localidad_id' =>309],
['nombre'=>'Sarmiento', 'localidad_id' =>307],
['nombre'=>'San Pantaleon', 'localidad_id' =>354],
['nombre'=>'Nueva Esperanza', 'localidad_id' =>354],
['nombre'=>'El Quimilar', 'localidad_id' =>354],
['nombre'=>'Carlos Juarez', 'localidad_id' =>309],
['nombre'=>'Sur', 'localidad_id' =>344],
['nombre'=>'Chino', 'localidad_id' =>210],
['nombre'=>'Villa Margarita', 'localidad_id' =>140],
['nombre'=>'Juan Diaz de Solis Viejo', 'localidad_id' =>2],
['nombre'=>'San Jose', 'localidad_id' =>290],
['nombre'=>'El Quebracho', 'localidad_id' =>210],
['nombre'=>'San Cayetano', 'localidad_id' =>364],
['nombre'=>'Los Paraisos', 'localidad_id' =>219],
['nombre'=>'Lujan', 'localidad_id' =>365],
['nombre'=>'Triangulo', 'localidad_id' =>23],
['nombre'=>'Sor Angela', 'localidad_id' =>23],
['nombre'=>'Villa Nueva', 'localidad_id' =>23],
['nombre'=>'12 de Octubre', 'localidad_id' =>23],
['nombre'=>'Centro', 'localidad_id' =>452],
['nombre'=>'San Cayetano', 'localidad_id' =>365],
['nombre'=>'San Francisco', 'localidad_id' =>444],
['nombre'=>'Tres', 'localidad_id' =>266],
['nombre'=>'Aerolito', 'localidad_id' =>356],
['nombre'=>'Santa Rita', 'localidad_id' =>356],
['nombre'=>'Virgen del Carballo', 'localidad_id' =>23],
['nombre'=>'Norte', 'localidad_id' =>403],
['nombre'=>'Gutierrez', 'localidad_id' =>160],
['nombre'=>'Rincon Viejo', 'localidad_id' =>140],
['nombre'=>'El Ojo', 'localidad_id' =>140],
['nombre'=>'El Mistolar', 'localidad_id' =>354],
['nombre'=>'Las Lomas', 'localidad_id' =>219],
['nombre'=>'Bicentenario', 'localidad_id' =>219],
['nombre'=>'Loro Pozo', 'localidad_id' =>199],
['nombre'=>'San Antonio', 'localidad_id' =>199],
['nombre'=>'FortÃ­n', 'localidad_id' =>352],
['nombre'=>'Nuevo', 'localidad_id' =>352],
['nombre'=>'Universitario', 'localidad_id' =>2],
['nombre'=>'YPF', 'localidad_id' =>219],
['nombre'=>'San Roque', 'localidad_id' =>219],
['nombre'=>'Aeropuerto', 'localidad_id' =>219],
['nombre'=>'Sr Mailin', 'localidad_id' =>444],
['nombre'=>'Centro', 'localidad_id' =>444],
['nombre'=>'El Canal', 'localidad_id' =>425],
['nombre'=>'San Cayetano', 'localidad_id' =>444],
['nombre'=>'Apache', 'localidad_id' =>403],
['nombre'=>'3 de abril', 'localidad_id' =>403],
['nombre'=>'Jarillal', 'localidad_id' =>403],
['nombre'=>'San Ramon', 'localidad_id' =>403],
['nombre'=>'San Antonio', 'localidad_id' =>403],
['nombre'=>'11 de Noviembre', 'localidad_id' =>403],
['nombre'=>'Centro', 'localidad_id' =>266],
['nombre'=>'La Florida', 'localidad_id' =>276],
['nombre'=>'La Plata', 'localidad_id' =>276],
['nombre'=>'Avellaneda', 'localidad_id' =>276],
['nombre'=>'Aeropuerto', 'localidad_id' =>199],
['nombre'=>'Los Alamos', 'localidad_id' =>2],
['nombre'=>'Campo Rosso', 'localidad_id' =>478],
['nombre'=>'La Guarida', 'localidad_id' =>154],
['nombre'=>'Belgrano Sur', 'localidad_id' =>262],
['nombre'=>'San Martin', 'localidad_id' =>262],
['nombre'=>'Rivadavia', 'localidad_id' =>262],
['nombre'=>'Matadero Viejo', 'localidad_id' =>262],
['nombre'=>'Matadero', 'localidad_id' =>262],
['nombre'=>'Estrella Roja', 'localidad_id' =>266],
['nombre'=>'Tala Pozo', 'localidad_id' =>266],
['nombre'=>'Norte', 'localidad_id' =>267],
['nombre'=>'Sur', 'localidad_id' =>267],
['nombre'=>'Centro', 'localidad_id' =>267],
['nombre'=>'Esperanza', 'localidad_id' =>276],
['nombre'=>'Municipal', 'localidad_id' =>276],
['nombre'=>'Colonia San Francisco', 'localidad_id' =>288],
['nombre'=>'50 Viviendas', 'localidad_id' =>290],
['nombre'=>'Lote 42', 'localidad_id' =>290],
['nombre'=>'Norte', 'localidad_id' =>290],
['nombre'=>'Los Inmigrantes', 'localidad_id' =>290],
['nombre'=>'Matadero', 'localidad_id' =>290],
['nombre'=>'Silencio', 'localidad_id' =>290],
['nombre'=>'San Roque', 'localidad_id' =>452],
['nombre'=>'Los Alamos', 'localidad_id' =>452],
['nombre'=>'Lujan', 'localidad_id' =>452],
['nombre'=>'Francisco 1Âº', 'localidad_id' =>466],
['nombre'=>'Foprovi', 'localidad_id' =>466],
['nombre'=>'Ferroviarios', 'localidad_id' =>403],
['nombre'=>'Los Telares', 'localidad_id' =>444],
['nombre'=>'San Cayetano', 'localidad_id' =>219],
['nombre'=>'El Escondido', 'localidad_id' =>219],
['nombre'=>'San Martin', 'localidad_id' =>315],
['nombre'=>'Arenal', 'localidad_id' =>315],
['nombre'=>'San Vicente', 'localidad_id' =>315],
['nombre'=>'Cabezas', 'localidad_id' =>315],
['nombre'=>'Belgrano Norte', 'localidad_id' =>356],
['nombre'=>'Santa Rosa', 'localidad_id' =>354],
['nombre'=>'Aeropuerto', 'localidad_id' =>355],
['nombre'=>'San Martin', 'localidad_id' =>355],
['nombre'=>'Quilmes', 'localidad_id' =>355],
['nombre'=>'Avenida', 'localidad_id' =>355],
['nombre'=>'20 Viviendas', 'localidad_id' =>242],
['nombre'=>'Campo I', 'localidad_id' =>242],
['nombre'=>'El Condor', 'localidad_id' =>262],
['nombre'=>'Sur', 'localidad_id' =>332],
['nombre'=>'Campo Cejas', 'localidad_id' =>266],
['nombre'=>'Lemos', 'localidad_id' =>266],
['nombre'=>'Norte', 'localidad_id' =>332],
['nombre'=>'Centro', 'localidad_id' =>332],
['nombre'=>'Matadero', 'localidad_id' =>332],
['nombre'=>'El ChaÃ±ar', 'localidad_id' =>332],
['nombre'=>'10 viviendas', 'localidad_id' =>266],
['nombre'=>'Malvinas', 'localidad_id' =>452],
['nombre'=>'Santa Rita', 'localidad_id' =>452],
['nombre'=>'San Carlos', 'localidad_id' =>309],
['nombre'=>'Santa Rita', 'localidad_id' =>311],
['nombre'=>'Obrero Norte', 'localidad_id' =>288],
['nombre'=>'Obrero Sur', 'localidad_id' =>288],
['nombre'=>'Centro', 'localidad_id' =>425],
['nombre'=>'Virgen de Sumampa', 'localidad_id' =>444],
['nombre'=>'Matadero', 'localidad_id' =>403],
['nombre'=>'Mailin', 'localidad_id' =>315],
['nombre'=>'Belgrano', 'localidad_id' =>22],
['nombre'=>'Centro', 'localidad_id' =>22],
['nombre'=>'San Cristobal', 'localidad_id' =>22],
['nombre'=>'Lasalle', 'localidad_id' =>315],
['nombre'=>'Talleres', 'localidad_id' =>219],
['nombre'=>'1Âº de Abril', 'localidad_id' =>315],
['nombre'=>'60 Viviendas', 'localidad_id' =>354],
['nombre'=>'Canal de Dios', 'localidad_id' =>354],
['nombre'=>'Los Rolos', 'localidad_id' =>426],
['nombre'=>'Nuestra Sra de la Paz', 'localidad_id' =>426],
['nombre'=>'El Rincon', 'localidad_id' =>210],
['nombre'=>'Sur', 'localidad_id' =>315],
['nombre'=>'Obras sanitarias', 'localidad_id' =>315],
['nombre'=>'Virgen del Valle', 'localidad_id' =>242],
['nombre'=>'Sarmiento', 'localidad_id' =>22],
['nombre'=>'San Expedito', 'localidad_id' =>22],
['nombre'=>'General Bores', 'localidad_id' =>22],
['nombre'=>'El Rosedal', 'localidad_id' =>22],
['nombre'=>'Belgrano', 'localidad_id' =>22],
['nombre'=>'Mataderos', 'localidad_id' =>22],
['nombre'=>'Virgen de Huachara', 'localidad_id' =>22],
['nombre'=>'Costanera', 'localidad_id' =>22],
['nombre'=>'San Cayetano', 'localidad_id' =>22],
['nombre'=>'Lourdes', 'localidad_id' =>23],
['nombre'=>'El Canal', 'localidad_id' =>344],
['nombre'=>'Finca de Ramos', 'localidad_id' =>140],
['nombre'=>'San Isidro', 'localidad_id' =>219],
['nombre'=>'Campo Santo', 'localidad_id' =>356],
['nombre'=>'La Balanza', 'localidad_id' =>356],
['nombre'=>'Begrano Sur', 'localidad_id' =>356],
['nombre'=>'Lourdes', 'localidad_id' =>344],
['nombre'=>'El Deancito', 'localidad_id' =>2],
['nombre'=>'1Âº Ampliacion Borges', 'localidad_id' =>2],
['nombre'=>'Las Mercedes', 'localidad_id' =>242],
['nombre'=>'El Canal', 'localidad_id' =>23],
['nombre'=>'Los Morales', 'localidad_id' =>2],
['nombre'=>'El Puestito', 'localidad_id' =>140],
['nombre'=>'Las Tijeras', 'localidad_id' =>140],
['nombre'=>'Los Alamos 3', 'localidad_id' =>140],
['nombre'=>'Lomas del Golf', 'localidad_id' =>2],
['nombre'=>'Villa Zanjon', 'localidad_id' =>24],
['nombre'=>'Parque Municipal', 'localidad_id' =>140],
['nombre'=>'Parque Industrial', 'localidad_id' =>140],
['nombre'=>'Malvinas Argentinas', 'localidad_id' =>160],
['nombre'=>'Los Quiroga', 'localidad_id' =>2],
['nombre'=>'Matadero', 'localidad_id' =>160],
['nombre'=>'Presidente Peron', 'localidad_id' =>23],
['nombre'=>'25 de Mayo Amp 540 Viviendas', 'localidad_id' =>140],
['nombre'=>'Jerarquizado Municipal', 'localidad_id' =>140],
['nombre'=>'San Javier II', 'localidad_id' =>140],
['nombre'=>'Nuevo San Carlos', 'localidad_id' =>140],
['nombre'=>'AmpliaciÃ³n Gorriti', 'localidad_id' =>140],
['nombre'=>'25 de Mayo 250 Viviendas', 'localidad_id' =>140],
['nombre'=>'San Antonio', 'localidad_id' =>140],
['nombre'=>'San Joaquin', 'localidad_id' =>354],
['nombre'=>'La Pista', 'localidad_id' =>354],
['nombre'=>'Pte. Peron', 'localidad_id' =>354],
['nombre'=>'San Cayetano', 'localidad_id' =>354],
['nombre'=>'Alberdi', 'localidad_id' =>354],
['nombre'=>'El Arbolito', 'localidad_id' =>356],
['nombre'=>'Barrio Norte', 'localidad_id' =>356],
['nombre'=>'El Obrador', 'localidad_id' =>356],
['nombre'=>'San Pantaleon', 'localidad_id' =>356],
['nombre'=>'San Cayetano', 'localidad_id' =>356],
['nombre'=>'Polideportivo', 'localidad_id' =>356],
['nombre'=>'17 de Noviembre', 'localidad_id' =>356],
['nombre'=>'Eva Peron', 'localidad_id' =>356],
['nombre'=>'Centro', 'localidad_id' =>356],
['nombre'=>'Belgrano Centro', 'localidad_id' =>356],
['nombre'=>'Villa Tranquila', 'localidad_id' =>356],
['nombre'=>'San Antonio', 'localidad_id' =>356],
['nombre'=>'Barrio Sur', 'localidad_id' =>356],
['nombre'=>'Matadero', 'localidad_id' =>315],
['nombre'=>'Madera Dura', 'localidad_id' =>315],
['nombre'=>'Rivas Jordan', 'localidad_id' =>315],
['nombre'=>'Eva Peron', 'localidad_id' =>315],
['nombre'=>'Belgrano', 'localidad_id' =>315],
['nombre'=>'Los Sosa', 'localidad_id' =>315],
['nombre'=>'FO.NA.VI.', 'localidad_id' =>315],
['nombre'=>'PRO.VI.PO.', 'localidad_id' =>315],
['nombre'=>'Alberdi', 'localidad_id' =>315],
['nombre'=>'FO.PRO.VI.', 'localidad_id' =>315],
['nombre'=>'Belgrano Norte', 'localidad_id' =>23],
['nombre'=>'Islas Malvinas', 'localidad_id' =>23]
        ];
        Barrio::insert($barrios);
    }
} 