<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Departamento;

class DepartamentoSeeder extends Seeder
{
    public function run()
    {
        $departamentos = [
            ['nombre' => 'Aguirre', 'provincia_id' => 1],
            ['nombre' => 'Alberdi', 'provincia_id' => 1],
            ['nombre' => 'Atamisqui', 'provincia_id' => 1],
            ['nombre' => 'Avellaneda', 'provincia_id' => 1],
            ['nombre' => 'Banda', 'provincia_id' => 1],
            ['nombre' => 'Belgrano', 'provincia_id' => 1],
            ['nombre' => 'Capital', 'provincia_id' => 1],
            ['nombre' => 'Choya', 'provincia_id' => 1],
            ['nombre' => 'Copo', 'provincia_id' => 1],
            ['nombre' => 'Figueroa', 'provincia_id' => 1],
            ['nombre' => 'Gral. Taboada', 'provincia_id' => 1],
            ['nombre' => 'Guasayán', 'provincia_id' => 1],
            ['nombre' => 'Jiménez', 'provincia_id' => 1],
            ['nombre' => 'J. F. Ibarra', 'provincia_id' => 1],
            ['nombre' => 'Loreto', 'provincia_id' => 1],
            ['nombre' => 'Mitre', 'provincia_id' => 1],
            ['nombre' => 'Moreno', 'provincia_id' => 1],
            ['nombre' => 'Ojo de Agua', 'provincia_id' => 1],
            ['nombre' => 'Pellegrini', 'provincia_id' => 1],
            ['nombre' => 'Quebrachos', 'provincia_id' => 1],
            ['nombre' => 'Río Hondo', 'provincia_id' => 1],
            ['nombre' => 'Rivadavia', 'provincia_id' => 1],
            ['nombre' => 'Robles', 'provincia_id' => 1],
            ['nombre' => 'Salavina', 'provincia_id' => 1],
            ['nombre' => 'San Martin', 'provincia_id' => 1],
            ['nombre' => 'Sarmiento', 'provincia_id' => 1],
            ['nombre' => 'Silípica', 'provincia_id' => 1],
            ['nombre' => 'Comuna 1', 'provincia_id' => 24],
            ['nombre' => 'Comuna 2', 'provincia_id' => 24],
            ['nombre' => 'Comuna 3', 'provincia_id' => 24],
            ['nombre' => 'Comuna 4', 'provincia_id' => 24],
            ['nombre' => 'Comuna 5', 'provincia_id' => 24],
            ['nombre' => 'Comuna 6', 'provincia_id' => 24],
            ['nombre' => 'Comuna 7', 'provincia_id' => 24],
            ['nombre' => 'Comuna 8', 'provincia_id' => 24],
            ['nombre' => 'Comuna 9', 'provincia_id' => 24],
            ['nombre' => 'Comuna 10', 'provincia_id' => 24],
            ['nombre'=> 'Comuna 11', 'provincia_id' => 24],
            ['nombre' => 'Comuna 12', 'provincia_id' => 24],
            ['nombre' => 'Comuna 13', 'provincia_id' => 24],
            ['nombre' => 'Comuna 14', 'provincia_id' => 24],
            ['nombre' => 'Comuna 15', 'provincia_id' => 24],
            ['nombre' => 'Adolfo Alsina', 'provincia_id' => 2],
            ['nombre' => 'Adolfo Gonzales Chaves', 'provincia_id' => 2],
            ['nombre' => 'Alberti', 'provincia_id' => 2],
            ['nombre' => 'Almirante Brown', 'provincia_id' => 2],
            ['nombre' => 'Avellaneda', 'provincia_id' => 2],
            ['nombre' => 'Ayacucho', 'provincia_id' => 2],
            ['nombre' => 'Azul', 'provincia_id' => 2],
            ['nombre' => 'Bahía Blanca', 'provincia_id' => 2],
            ['nombre' => 'Balcarce', 'provincia_id' => 2],
            ['nombre' => 'Baradero', 'provincia_id' => 2],
            ['nombre' => 'Arrecifes', 'provincia_id' => 2],
            ['nombre' => 'Benito Juárez', 'provincia_id' => 2],
            ['nombre' => 'Berazategui', 'provincia_id' => 2],
            ['nombre' => 'Berisso', 'provincia_id' => 2],
            ['nombre' => 'Bolívar', 'provincia_id' => 2],
            ['nombre' => 'Bragado', 'provincia_id' => 2],
            ['nombre' => 'Brandsen', 'provincia_id' => 2],
            ['nombre' => 'Campana', 'provincia_id' => 2],
            ['nombre' => 'Cañuelas', 'provincia_id' => 2],
            ['nombre' => 'Capitán Sarmiento', 'provincia_id' => 2],
            ['nombre' => 'Carlos Casares', 'provincia_id' => 2],
            ['nombre' => 'Carlos Tejedor', 'provincia_id' => 2],
            ['nombre' => 'Carmen de Areco', 'provincia_id' => 2],
            ['nombre' => 'Castelli', 'provincia_id' => 2],
            ['nombre' => 'Colón', 'provincia_id' => 2],
            ['nombre' => 'Coronel de Marina Leonardo Rosales', 'provincia_id' => 2],
            ['nombre' => 'Coronel Dorrego', 'provincia_id' => 2],
            ['nombre' => 'Coronel Pringles', 'provincia_id' => 2],
            ['nombre' => 'Coronel Suárez', 'provincia_id' => 2],
            ['nombre' => 'Chacabuco', 'provincia_id' => 2],
            ['nombre' => 'Chascomús', 'provincia_id' => 2],
            ['nombre' => 'Chivilcoy', 'provincia_id' => 2],
            ['nombre' => 'Daireaux', 'provincia_id' => 2],
            ['nombre' => 'Dolores', 'provincia_id' => 2],
            ['nombre' => 'Ensenada', 'provincia_id' => 2],
            ['nombre' => 'Escobar', 'provincia_id' => 2],
            ['nombre' => 'Esteban Echeverría', 'provincia_id' => 2],
            ['nombre' => 'Exaltación de la Cruz', 'provincia_id' => 2],
            ['nombre' => 'Ezeiza', 'provincia_id' => 2],
            ['nombre' => 'Florencio Varela', 'provincia_id' => 2],
            ['nombre' => 'Florentino Ameghino', 'provincia_id' => 2],
            ['nombre' => 'General Alvarado', 'provincia_id' => 2],
            ['nombre' => 'General Alvear', 'provincia_id' => 2],
            ['nombre' => 'General Arenales', 'provincia_id' => 2],
            ['nombre' => 'General Belgrano', 'provincia_id' => 2],
            ['nombre' => 'General Guido', 'provincia_id' => 2],
            ['nombre' => 'General Juan Madariaga', 'provincia_id' => 2],
            ['nombre' => 'General La Madrid', 'provincia_id' => 2],
            ['nombre' => 'General Las Heras', 'provincia_id' => 2],
            ['nombre' => 'General Lavalle', 'provincia_id' => 2],
            ['nombre' => 'General Paz', 'provincia_id' => 2],
            ['nombre' => 'General Pinto', 'provincia_id' => 2],
            ['nombre' => 'General Pueyrredón', 'provincia_id' => 2],
            ['nombre' => 'General Rodríguez', 'provincia_id' => 2],
            ['nombre' => 'General San Martín', 'provincia_id' => 2],
            ['nombre' => 'General Viamonte', 'provincia_id' => 2],
            ['nombre' => 'General Villegas', 'provincia_id' => 2],
            ['nombre' => 'Guaminí', 'provincia_id' => 2],
            ['nombre' => 'Hipólito Yrigoyen', 'provincia_id' => 2],
            ['nombre' => 'Hurlingham', 'provincia_id' => 2],
            ['nombre' => 'Ituzaingó', 'provincia_id' => 2],
            ['nombre' => 'José C. Paz', 'provincia_id' => 2],
            ['nombre' => 'Junín', 'provincia_id' => 2],
            ['nombre' => 'La Costa', 'provincia_id' => 2],
            ['nombre' => 'La Matanza', 'provincia_id' => 2],
            ['nombre' => 'Lanús', 'provincia_id' => 2],
            ['nombre' => 'La Plata', 'provincia_id' => 2],
            ['nombre' => 'Laprida', 'provincia_id' => 2],
            ['nombre' => 'Las Flores', 'provincia_id' => 2],
            ['nombre' => 'Leandro N. Alem', 'provincia_id' => 2],
            ['nombre' => 'Lincoln', 'provincia_id' => 2],
            ['nombre' => 'Lobería', 'provincia_id' => 2],
            ['nombre' => 'Lobos', 'provincia_id' => 2],
            ['nombre' => 'Lomas de Zamora', 'provincia_id' => 2],
            ['nombre' => 'Luján', 'provincia_id' => 2],
            ['nombre' => 'Magdalena', 'provincia_id' => 2],
            ['nombre' => 'Maipú', 'provincia_id' => 2],
            ['nombre' => 'Malvinas Argentinas', 'provincia_id' => 2],
            ['nombre' => 'Mar Chiquita', 'provincia_id' => 2],
            ['nombre' => 'Marcos Paz', 'provincia_id' => 2],
            ['nombre' => 'Mercedes', 'provincia_id' => 2],
            ['nombre' => 'Merlo', 'provincia_id' => 2],
            ['nombre' => 'Monte', 'provincia_id' => 2],
            ['nombre' => 'Monte Hermoso', 'provincia_id' => 2],
            ['nombre' => 'Moreno', 'provincia_id' => 2],
            ['nombre' => 'Morón', 'provincia_id' => 2],
            ['nombre' => 'Navarro', 'provincia_id' => 2],
            ['nombre' => 'Necochea', 'provincia_id' => 2],
            ['nombre' => '9 de Julio', 'provincia_id' => 2],
            ['nombre' => 'Olavarría', 'provincia_id' => 2],
            ['nombre' => 'Patagones', 'provincia_id' => 2],
            ['nombre' => 'Pehuajó', 'provincia_id' => 2],
            ['nombre' => 'Pellegrini', 'provincia_id' => 2],
            ['nombre' => 'Pergamino', 'provincia_id' => 2],
            ['nombre' => 'Pila', 'provincia_id' => 2],
            ['nombre' => 'Pilar', 'provincia_id' => 2],
            ['nombre' => 'Pinamar', 'provincia_id' => 2],
            ['nombre' => 'Presidente Perón', 'provincia_id' => 2],
            ['nombre' => 'Puán', 'provincia_id' => 2],
            ['nombre' => 'Punta Indio', 'provincia_id' => 2],
            ['nombre' => 'Quilmes', 'provincia_id' => 2],
            ['nombre' => 'Ramallo', 'provincia_id' => 2],
            ['nombre' => 'Rauch', 'provincia_id' => 2],
            ['nombre' => 'Rivadavia', 'provincia_id' => 2],
            ['nombre' => 'Rojas', 'provincia_id' => 2],
            ['nombre' => 'Roque Pérez', 'provincia_id' => 2],
            ['nombre' => 'Saavedra', 'provincia_id' => 2],
            ['nombre' => 'Saladillo', 'provincia_id' => 2],
            ['nombre' => 'Salto', 'provincia_id' => 2],
            ['nombre' => 'Salliqueló', 'provincia_id' => 2],
            ['nombre' => 'San Andrés de Giles', 'provincia_id' => 2],
            ['nombre' => 'San Antonio de Areco', 'provincia_id' => 2],
            ['nombre' => 'San Cayetano', 'provincia_id' => 2],
            ['nombre'=> 'San Fernando', 'provincia_id' => 2],
            ['nombre' => 'San Isidro', 'provincia_id' => 2],
            ['nombre' => 'San Miguel', 'provincia_id' => 2],
            ['nombre' => 'San Nicolás', 'provincia_id' => 2],
            ['nombre' => 'San Pedro', 'provincia_id' => 2],
            ['nombre' => 'San Vicente', 'provincia_id' => 2],
            ['nombre' => 'Suipacha', 'provincia_id' => 2],
            ['nombre' => 'Tandil', 'provincia_id' => 2],
            ['nombre' => 'Tapalqué', 'provincia_id' => 2],
            ['nombre' => 'Tigre', 'provincia_id' => 2],
            ['nombre' => 'Tordillo', 'provincia_id' => 2],
            ['nombre' => 'Tornquist', 'provincia_id' => 2],
            ['nombre' => 'Trenque Lauquen', 'provincia_id' => 2],
            ['nombre' => 'Tres Arroyos', 'provincia_id' => 2],
            ['nombre' => 'Tres de Febrero', 'provincia_id' => 2],
            ['nombre' => 'Tres Lomas', 'provincia_id' => 2],
            ['nombre' => '25 de Mayo', 'provincia_id' => 2],
            ['nombre' => 'Vicente López', 'provincia_id' => 2],
            ['nombre' => 'Villa Gesell', 'provincia_id' => 2],
            ['nombre' => 'Villarino', 'provincia_id' => 2],
            ['nombre' => 'Zárate', 'provincia_id' => 2],
            ['nombre' => 'Ambato', 'provincia_id' => 3],
            ['nombre' => 'Ancasti', 'provincia_id' => 3],
            ['nombre' => 'Andalgalá', 'provincia_id' => 3],
            ['nombre' => 'Antofagasta de la Sierra', 'provincia_id' => 3],
            ['nombre' => 'Belén', 'provincia_id' => 3],
            ['nombre' => 'Capayán', 'provincia_id' => 3],
            ['nombre' => 'Capital', 'provincia_id' => 3],
            ['nombre' => 'El Alto', 'provincia_id' => 3],
            ['nombre' => 'Fray Mamerto Esquiú', 'provincia_id' => 3],
            ['nombre' => 'La Paz', 'provincia_id' => 3],
            ['nombre' => 'Paclín', 'provincia_id' => 3],
            ['nombre' => 'Pomán', 'provincia_id' => 3],
            ['nombre' => 'Santa María', 'provincia_id' => 3],
            ['nombre' => 'Santa Rosa', 'provincia_id' => 3],
            ['nombre' => 'Tinogasta', 'provincia_id' => 3],
            ['nombre' => 'Valle Viejo', 'provincia_id' => 3],
            ['nombre' => 'Calamuchita', 'provincia_id' => 6],
            ['nombre' => 'Capital', 'provincia_id' => 6],
            ['nombre' => 'Colón', 'provincia_id' => 6],
            ['nombre' => 'Cruz del Eje', 'provincia_id' => 6],
            ['nombre' => 'General Roca', 'provincia_id' => 6],
            ['nombre' => 'General San Martín', 'provincia_id' => 6],
            ['nombre' => 'Ischilín', 'provincia_id' => 6],
            ['nombre' => 'Juárez Celman', 'provincia_id' => 6],
            ['nombre' => 'Marcos Juárez', 'provincia_id' => 6],
            ['nombre' => 'Minas', 'provincia_id' => 6],
            ['nombre' => 'Pocho', 'provincia_id' => 6],
            ['nombre' => 'Presidente Roque Sáenz Peña', 'provincia_id' => 6],
            ['nombre' => 'Punilla', 'provincia_id' => 6],
            ['nombre' => 'Río Cuarto', 'provincia_id' => 6],
            ['nombre' => 'Río Primero', 'provincia_id' => 6],
            ['nombre' => 'Río Seco', 'provincia_id' => 6],
            ['nombre' => 'Río Segundo', 'provincia_id' => 6],
            ['nombre' => 'San Alberto', 'provincia_id' => 6],
            ['nombre' => 'San Javier', 'provincia_id' => 6],
            ['nombre' => 'San Justo', 'provincia_id' => 6],
            ['nombre' => 'Santa María', 'provincia_id' => 6],
            ['nombre' => 'Sobremonte', 'provincia_id' => 6],
            ['nombre' => 'Tercero Arriba', 'provincia_id' => 6],
            ['nombre' => 'Totoral', 'provincia_id' => 6],
            ['nombre' => 'Tulumba', 'provincia_id' => 6],
            ['nombre' => 'Unión', 'provincia_id' => 6],
            ['nombre' => 'Bella Vista', 'provincia_id' => 7],
            ['nombre' => 'Berón de Astrada', 'provincia_id' => 7],
            ['nombre' => 'Capital', 'provincia_id' => 7],
            ['nombre' => 'Concepción', 'provincia_id' => 7],
            ['nombre' => 'Curuzú Cuatiá', 'provincia_id' => 7],
            ['nombre' => 'Empedrado', 'provincia_id' => 7],
            ['nombre' => 'Esquina', 'provincia_id' => 7],
            ['nombre' => 'General Alvear', 'provincia_id' => 7],
            ['nombre' => 'General Paz', 'provincia_id' => 7],
            ['nombre' => 'Goya', 'provincia_id' => 7],
            ['nombre' => 'Itatí', 'provincia_id' => 7],
            ['nombre' => 'Ituzaingó', 'provincia_id' => 7],
            ['nombre' => 'Lavalle', 'provincia_id' => 7],
            ['nombre' => 'Mburucuyá', 'provincia_id' => 7],
            ['nombre' => 'Mercedes', 'provincia_id' => 7],
            ['nombre' => 'Monte Caseros', 'provincia_id' => 7],
            ['nombre' => 'Paso de los Libres', 'provincia_id' => 7],
            ['nombre' => 'Saladas', 'provincia_id' => 7],
            ['nombre' => 'San Cosme', 'provincia_id' => 7],
            ['nombre' => 'San Luis del Palmar', 'provincia_id' => 7],
            ['nombre' => 'San Martín', 'provincia_id' => 7],
            ['nombre' => 'San Miguel', 'provincia_id' => 7],
            ['nombre' => 'San Roque', 'provincia_id' => 7],
            ['nombre' => 'Santo Tomé', 'provincia_id' => 7],
            ['nombre' => 'Sauce', 'provincia_id' => 7],
            ['nombre' => 'Almirante Brown', 'provincia_id' => 4],
            ['nombre' => 'Bermejo', 'provincia_id' => 4],
            ['nombre' => 'Comandante Fernández', 'provincia_id' => 4],
            ['nombre' => 'Chacabuco', 'provincia_id' => 4],
            ['nombre' => '12 de Octubre', 'provincia_id' => 4],
            ['nombre' => '2 de Abril', 'provincia_id' => 4],
            ['nombre' => 'Fray Justo Santa María de Oro', 'provincia_id' => 4],
            ['nombre' => 'General Belgrano', 'provincia_id' => 4],
            ['nombre' => 'General Donovan', 'provincia_id' => 4],
            ['nombre' => 'General Güemes', 'provincia_id' => 4],
            ['nombre' => 'Independencia', 'provincia_id' => 4],
            ['nombre' => 'Libertad', 'provincia_id' => 4],
            ['nombre' => 'Libertador General San Martín', 'provincia_id' => 4],
            ['nombre' => 'Maipú', 'provincia_id' => 4],
            ['nombre' => 'Mayor Luis J. Fontana', 'provincia_id' => 4],
            ['nombre' => '9 de Julio', 'provincia_id' => 4],
            ['nombre' => 'OHiggins', 'provincia_id' => 4],
            ['nombre' => 'Presidencia de la Plaza', 'provincia_id' => 4],
            ['nombre' => '1º de Mayo', 'provincia_id' => 4],
            ['nombre' => 'Quitilipi', 'provincia_id' => 4],
            ['nombre' => 'San Fernando', 'provincia_id' => 4],
            ['nombre' => 'San Lorenzo', 'provincia_id' => 4],
            ['nombre' => 'Sargento Cabral', 'provincia_id' => 4],
            ['nombre' => 'Tapenagá', 'provincia_id' => 4],
            ['nombre' => '25 de Mayo', 'provincia_id' => 4],
            ['nombre' => 'Biedma', 'provincia_id' => 5],
            ['nombre' => 'Cushamen', 'provincia_id' => 5],
            ['nombre' => 'Escalante', 'provincia_id' => 5],
            ['nombre' => 'Florentino Ameghino', 'provincia_id' => 5],
            ['nombre' => 'Futaleufu', 'provincia_id' => 5],
            ['nombre' => 'Gaiman', 'provincia_id' => 5],
            ['nombre' => 'Gastre', 'provincia_id' => 5],
            ['nombre' => 'Languiñeo', 'provincia_id' => 5],
            ['nombre' => 'Martires', 'provincia_id' => 5],
            ['nombre' => 'Paso de Indios', 'provincia_id' => 5],
            ['nombre' => 'Rawson', 'provincia_id' => 5],
            ['nombre' => 'Río Senguer', 'provincia_id' => 5],
            ['nombre' => 'Sarmiento', 'provincia_id' => 5],
            ['nombre' => 'Tehuelches', 'provincia_id' => 5],
            ['nombre' => 'Telsen', 'provincia_id' => 5],
            ['nombre' => 'Colón', 'provincia_id' => 8],
            ['nombre' => 'Concordia', 'provincia_id' => 8],
            ['nombre' => 'Diamante', 'provincia_id' => 8],
            ['nombre' => 'Federación', 'provincia_id' => 8],
            ['nombre' => 'Federal', 'provincia_id' => 8],
            ['nombre' => 'Feliciano', 'provincia_id' => 8],
            ['nombre' => 'Gualeguay', 'provincia_id' => 8],
            ['nombre' => 'Gualeguaychú', 'provincia_id' => 8],
            ['nombre' => 'Islas del Ibicuy', 'provincia_id' => 8],
            ['nombre' => 'La Paz', 'provincia_id' => 8],
            ['nombre' => 'Nogoyá', 'provincia_id' => 8],
            ['nombre' => 'Paraná', 'provincia_id' => 8],
            ['nombre' => 'San Salvador', 'provincia_id' => 8],
            ['nombre' => 'Tala', 'provincia_id' => 8],
            ['nombre' => 'Uruguay', 'provincia_id' => 8],
            ['nombre' => 'Victoria', 'provincia_id' => 8],
            ['nombre' => 'Villaguay', 'provincia_id' => 8],
            ['nombre' => 'Bermejo', 'provincia_id' => 9],
            ['nombre' => 'Formosa', 'provincia_id' => 9],
            ['nombre' => 'Laishi', 'provincia_id' => 9],
            ['nombre' => 'Matacos', 'provincia_id' => 9],
            ['nombre' => 'Patiño', 'provincia_id' => 9],
            ['nombre' => 'Pilagás', 'provincia_id' => 9],
            ['nombre' => 'Pilcomayo', 'provincia_id' => 9],
            ['nombre' => 'Pirané', 'provincia_id' => 9],
            ['nombre' => 'Ramón Lista', 'provincia_id' => 9],
            ['nombre' => 'Cochinoca', 'provincia_id' => 10],
            ['nombre' => 'El Carmen', 'provincia_id' => 10],
            ['nombre' => 'Dr. Manuel Belgrano', 'provincia_id' => 10],
            ['nombre' => 'Humahuaca', 'provincia_id' => 10],
            ['nombre' => 'Ledesma', 'provincia_id' => 10],
            ['nombre' => 'Palpalá', 'provincia_id' => 10],
            ['nombre' => 'Rinconada', 'provincia_id' => 10],
            ['nombre' => 'San Antonio', 'provincia_id' => 10],
            ['nombre' => 'San Pedro', 'provincia_id' => 10],
            ['nombre' => 'Santa Bárbara', 'provincia_id' => 10],
            ['nombre' => 'Santa Catalina', 'provincia_id' => 10],
            ['nombre' => 'Susques', 'provincia_id' => 10],
            ['nombre' => 'Tilcara', 'provincia_id' => 10],
            ['nombre' => 'Tumbaya', 'provincia_id' => 10],
            ['nombre' => 'Valle Grande', 'provincia_id' => 10],
            ['nombre' => 'Yavi', 'provincia_id' => 10],
            ['nombre' => 'Atreucó', 'provincia_id' => 11],
            ['nombre' => 'Caleu Caleu', 'provincia_id' => 11],
            ['nombre' => 'Capital', 'provincia_id' => 11],
            ['nombre' => 'Catriló', 'provincia_id' => 11],
            ['nombre' => 'Conhelo', 'provincia_id' => 11],
            ['nombre' => 'Curacó', 'provincia_id' => 11],
            ['nombre' => 'Chalileo', 'provincia_id' => 11],
            ['nombre' => 'Chapaleufú', 'provincia_id' => 11],
            ['nombre' => 'Chical Co', 'provincia_id' => 11],
            ['nombre' => 'Guatraché', 'provincia_id' => 11],
            ['nombre' => 'Hucal', 'provincia_id' => 11],
            ['nombre' => 'Lihuel Calel', 'provincia_id' => 11],
            ['nombre' => 'Limay Mahuida', 'provincia_id' => 11],
            ['nombre' => 'Loventué', 'provincia_id' => 11],
            ['nombre' => 'Maracó', 'provincia_id' => 11],
            ['nombre' => 'Puelén', 'provincia_id' => 11],
            ['nombre' => 'Quemú Quemú', 'provincia_id' => 11],
            ['nombre' => 'Rancul', 'provincia_id' => 11],
            ['nombre' => 'Realicó', 'provincia_id' => 11],
            ['nombre' => 'Toay', 'provincia_id' => 11],
            ['nombre' => 'Trenel', 'provincia_id' => 11],
            ['nombre' => 'Utracán', 'provincia_id' => 11],
            ['nombre' => 'Arauco', 'provincia_id' => 12],
            ['nombre' => 'Capital', 'provincia_id' => 12],
            ['nombre' => 'Castro Barros', 'provincia_id' => 12],
            ['nombre' => 'Coronel Felipe Varela', 'provincia_id' => 12],
            ['nombre' => 'Chamical', 'provincia_id' => 12],
            ['nombre' => 'Chilecito', 'provincia_id' => 12],
            ['nombre' => 'Famatina', 'provincia_id' => 12],
            ['nombre' => 'General Ángel V. Peñaloza', 'provincia_id' => 12],
            ['nombre' => 'General Belgrano', 'provincia_id' => 12],
            ['nombre' => 'General Juan Facundo Quiroga', 'provincia_id' => 12],
            ['nombre' => 'General Lamadrid', 'provincia_id' => 12],
            ['nombre' => 'General Ocampo', 'provincia_id' => 12],
            ['nombre' => 'General San Martín', 'provincia_id' => 12],
            ['nombre' => 'Vinchina', 'provincia_id' => 12],
            ['nombre' => 'Independencia', 'provincia_id' => 12],
            ['nombre' => 'Rosario Vera Peñaloza', 'provincia_id' => 12],
            ['nombre' => 'San Blas de los Sauces', 'provincia_id' => 12],
            ['nombre' => 'Sanagasta', 'provincia_id' => 12],
            ['nombre' => 'Capital', 'provincia_id' => 13],
            ['nombre' => 'General Alvear', 'provincia_id' => 13],
            ['nombre' => 'Godoy Cruz', 'provincia_id' => 13],
            ['nombre' => 'Guaymallén', 'provincia_id' => 13],
            ['nombre' => 'Junín', 'provincia_id' => 13],
            ['nombre' => 'La Paz', 'provincia_id' => 13],
            ['nombre' => 'Las Heras', 'provincia_id' => 13],
            ['nombre' => 'Lavalle', 'provincia_id' => 13],
            ['nombre' => 'Luján de Cuyo', 'provincia_id' => 13],
            ['nombre' => 'Maipú', 'provincia_id' => 13],
            ['nombre' => 'Malargüe', 'provincia_id' => 13],
            ['nombre' => 'Rivadavia', 'provincia_id' => 13],
            ['nombre' => 'San Carlos', 'provincia_id' => 13],
            ['nombre' => 'San Martín', 'provincia_id' => 13],
            ['nombre' => 'San Rafael', 'provincia_id' => 13],
            ['nombre' => 'Santa Rosa', 'provincia_id' => 13],
            ['nombre' => 'Tunuyán', 'provincia_id' => 13],
            ['nombre' => 'Tupungato', 'provincia_id' => 13],
            ['nombre' => 'Apóstoles', 'provincia_id' => 14],
            ['nombre' => 'Cainguás', 'provincia_id' => 14],
            ['nombre' => 'Candelaria', 'provincia_id' => 14],
            ['nombre' => 'Capital', 'provincia_id' => 14],
            ['nombre' => 'Concepción', 'provincia_id' => 14],
            ['nombre' => 'Eldorado', 'provincia_id' => 14],
            ['nombre' => 'General Manuel Belgrano', 'provincia_id' => 14],
            ['nombre' => 'Guaraní', 'provincia_id' => 14],
            ['nombre' => 'Iguazú', 'provincia_id' => 14],
            ['nombre' => 'Leandro N. Alem', 'provincia_id' => 14],
            ['nombre' => 'Libertador General San Martín', 'provincia_id' => 14],
            ['nombre' => 'Montecarlo', 'provincia_id' => 14],
            ['nombre' => 'Oberá', 'provincia_id' => 14],
            ['nombre' => 'San Ignacio', 'provincia_id' => 14],
            ['nombre' => 'San Javier', 'provincia_id' => 14],
            ['nombre' => 'San Pedro', 'provincia_id' => 14],
            ['nombre' => '25 de Mayo', 'provincia_id' => 14],
            ['nombre' => 'Aluminé', 'provincia_id' => 15],
            ['nombre' => 'Añelo', 'provincia_id' => 15],
            ['nombre' => 'Catán Lil', 'provincia_id' => 15],
            ['nombre' => 'Collón Curá', 'provincia_id' => 15],
            ['nombre' => 'Confluencia', 'provincia_id' => 15],
            ['nombre' => 'Chos Malal', 'provincia_id' => 15],
            ['nombre' => 'Huiliches', 'provincia_id' => 15],
            ['nombre' => 'Lácar', 'provincia_id' => 15],
            ['nombre' => 'Loncopué', 'provincia_id' => 15],
            ['nombre' => 'Los Lagos', 'provincia_id' => 15],
            ['nombre' => 'Minas', 'provincia_id' => 15],
            ['nombre' => 'Ñorquín', 'provincia_id' => 15],
            ['nombre' => 'Pehuenches', 'provincia_id' => 15],
            ['nombre' => 'Picún Leufú', 'provincia_id' => 15],
            ['nombre' => 'Picunches', 'provincia_id' => 15],
            ['nombre' => 'Zapala', 'provincia_id' => 15],
            ['nombre' => 'Adolfo Alsina', 'provincia_id' => 16],
            ['nombre' => 'Avellaneda', 'provincia_id' => 16],
            ['nombre' => 'Bariloche', 'provincia_id' => 16],
            ['nombre' => 'Conesa', 'provincia_id' => 16],
            ['nombre' => 'El Cuy', 'provincia_id' => 16],
            ['nombre' => 'General Roca', 'provincia_id' => 16],
            ['nombre' => '9 de Julio', 'provincia_id' => 16],
            ['nombre' => 'Ñorquincó', 'provincia_id' => 16],
            ['nombre' => 'Pichi Mahuida', 'provincia_id' => 16],
            ['nombre' => 'Pilcaniyeu', 'provincia_id' => 16],
            ['nombre' => 'San Antonio', 'provincia_id' => 16],
            ['nombre' => 'Valcheta', 'provincia_id' => 16],
            ['nombre' => '25 de Mayo', 'provincia_id' => 16],
            ['nombre' => 'Anta', 'provincia_id' => 17],
            ['nombre' => 'Cachi', 'provincia_id' => 17],
            ['nombre' => 'Cafayate', 'provincia_id' => 17],
            ['nombre' => 'Capital', 'provincia_id' => 17],
            ['nombre' => 'Cerrillos', 'provincia_id' => 17],
            ['nombre' => 'Chicoana', 'provincia_id' => 17],
            ['nombre' => 'General Güemes', 'provincia_id' => 17],
            ['nombre' => 'General José de San Martín', 'provincia_id' => 17],
            ['nombre' => 'Guachipas', 'provincia_id' => 17],
            ['nombre' => 'Iruya', 'provincia_id' => 17],
            ['nombre' => 'La Caldera', 'provincia_id' => 17],
            ['nombre' => 'La Candelaria', 'provincia_id' => 17],
            ['nombre' => 'La Poma', 'provincia_id' => 17],
            ['nombre' => 'La Viña', 'provincia_id' => 17],
            ['nombre' => 'Los Andes', 'provincia_id' => 17],
            ['nombre' => 'Metán', 'provincia_id' => 17],
            ['nombre' => 'Molinos', 'provincia_id' => 17],
            ['nombre' => 'Orán', 'provincia_id' => 17],
            ['nombre' => 'Rivadavia', 'provincia_id' => 17],
            ['nombre' => 'Rosario de la Frontera', 'provincia_id' => 17],
            ['nombre' => 'Rosario de Lerma', 'provincia_id' => 17],
            ['nombre' => 'San Carlos', 'provincia_id' => 17],
            ['nombre' => 'Santa Victoria', 'provincia_id' => 17],
            ['nombre' => 'Albardón', 'provincia_id' => 18],
            ['nombre' => 'Angaco', 'provincia_id' => 18],
            ['nombre' => 'Calingasta', 'provincia_id' => 18],
            ['nombre' => 'Capital', 'provincia_id' => 18],
            ['nombre' => 'Caucete', 'provincia_id' => 18],
            ['nombre' => 'Chimbas', 'provincia_id' => 18],
            ['nombre' => 'Iglesia', 'provincia_id' => 18],
            ['nombre' => 'Jáchal', 'provincia_id' => 18],
            ['nombre' => '9 de Julio', 'provincia_id' => 18],
            ['nombre' => 'Pocito', 'provincia_id' => 18],
            ['nombre' => 'Rawson', 'provincia_id' => 18],
            ['nombre' => 'Rivadavia', 'provincia_id' => 18],
            ['nombre' => 'San Martín', 'provincia_id' => 18],
            ['nombre' => 'Santa Lucía', 'provincia_id' => 18],
            ['nombre' => 'Sarmiento', 'provincia_id' => 18],
            ['nombre' => 'Ullum', 'provincia_id' => 18],
            ['nombre' => 'Valle Fértil', 'provincia_id' => 18],
            ['nombre' => '25 de Mayo', 'provincia_id' => 18],
            ['nombre' => 'Zonda', 'provincia_id' => 18],
            ['nombre' => 'Ayacucho', 'provincia_id' => 19],
            ['nombre' => 'Belgrano', 'provincia_id' => 19],
            ['nombre' => 'Coronel Pringles', 'provincia_id' => 19],
            ['nombre' => 'Chacabuco', 'provincia_id' => 19],
            ['nombre' => 'General Pedernera', 'provincia_id' => 19],
            ['nombre' => 'Gobernador Dupuy', 'provincia_id' => 19],
            ['nombre' => 'Junín', 'provincia_id' => 19],
            ['nombre' => 'La Capital', 'provincia_id' => 19],
            ['nombre' => 'Libertador General San Martín', 'provincia_id' => 19],
            ['nombre' => 'Corpen Aike', 'provincia_id' => 20],
            ['nombre' => 'Deseado', 'provincia_id' => 20],
            ['nombre' => 'Güer Aike', 'provincia_id' => 20],
            ['nombre' => 'Lago Argentino', 'provincia_id' => 20],
            ['nombre' => 'Lago Buenos Aires', 'provincia_id' => 20],
            ['nombre' => 'Magallanes', 'provincia_id' => 20],
            ['nombre' => 'Río Chico', 'provincia_id' => 20],
            ['nombre' => 'Belgrano', 'provincia_id' => 21],
            ['nombre' => 'Caseros', 'provincia_id' => 21],
            ['nombre' => 'Castellanos', 'provincia_id' => 21],
            ['nombre' => 'Constitución', 'provincia_id' => 21],
            ['nombre' => 'Garay', 'provincia_id' => 21],
            ['nombre' => 'General López', 'provincia_id' => 21],
            ['nombre' => 'General Obligado', 'provincia_id' => 21],
            ['nombre' => 'Iriondo', 'provincia_id' => 21],
            ['nombre' => 'La Capital', 'provincia_id' => 21],
            ['nombre' => 'Las Colonias', 'provincia_id' => 21],
            ['nombre' => '9 de Julio', 'provincia_id' => 21],
            ['nombre' => 'Rosario', 'provincia_id' => 21],
            ['nombre' => 'San Cristóbal', 'provincia_id' => 21],
            ['nombre' => 'San Javier', 'provincia_id' => 21],
            ['nombre' => 'San Jerónimo', 'provincia_id' => 21],
            ['nombre' => 'San Justo', 'provincia_id' => 21],
            ['nombre' => 'San Lorenzo', 'provincia_id' => 21],
            ['nombre' => 'San Martín', 'provincia_id' => 21],
            ['nombre' => 'Vera', 'provincia_id' => 21],
            ['nombre' => 'Burruyacú', 'provincia_id' => 23],
            ['nombre' => 'Cruz Alta', 'provincia_id' => 23],
            ['nombre' => 'Chicligasta', 'provincia_id' => 23],
            ['nombre' => 'Famaillá', 'provincia_id' => 23],
            ['nombre' => 'Graneros', 'provincia_id' => 23],
            ['nombre' => 'Juan B. Alberdi', 'provincia_id' => 23],
            ['nombre' => 'La Cocha', 'provincia_id' => 23],
            ['nombre' => 'Leales', 'provincia_id' => 23],
            ['nombre' => 'Lules', 'provincia_id' => 23],
            ['nombre' => 'Monteros', 'provincia_id' => 23],
            ['nombre' => 'Río Chico', 'provincia_id' => 23],
            ['nombre' => 'Capital', 'provincia_id' => 23],
            ['nombre' => 'Simoca', 'provincia_id' => 23],
            ['nombre' => 'Tafí del Valle', 'provincia_id' => 23],
            ['nombre' => 'Tafí Viejo', 'provincia_id' => 23],
            ['nombre' => 'Trancas', 'provincia_id' => 23],
            ['nombre' => 'Yerba Buena', 'provincia_id' => 23],
            ['nombre' => 'Río Grande', 'provincia_id' => 22],
            ['nombre' => 'Ushuaia', 'provincia_id' => 22],
            ['nombre' => 'Islas del Atlántico Sur', 'provincia_id' => 22],
            ['nombre' => 'Antártida Argentina', 'provincia_id' => 22],
        ];
            
        Departamento::insert($departamentos);
    }
} 